### PR TITLE
adding connection timeout in secs with default value 10 secs

### PR DESCRIPTION
**Pull request by skoky**
- adding connection timeout when opening socket to the device as an optional value with default 10 secs. Relates to #171 
- small code formatting. Sorry for that, my IDE insists on this
- please add or review python code / sample if we maybe need to describe it in more details

### CODE REVIEW

**Comment by skoky** [comment]
> ```rust
> ApiClient::new(tapo_username, tapo_password)?
> ```

Yes, you are right, its probably more clean usage as you describe. But its much more difficult to implement as the `ApiClient` does not store client directly but protocol. And this is immutable and private.This would need bigger re-factoring. 

In the current `ApiClient::new` there is HttpClient builder where we can set the timeout. And the `timeout_secs` is an optional value. Not mandatory.

**Comment by skoky** [comment]
I updated one python example `tapo_p100.py` with shorter timeout than defualt 10secs. I used 3 secs. Its optional value and default value is 10 secs as you suggested

**Comment by mihai-dinculescu** [comment]
I went ahead and did the refactor. It was a pain indeed, as you've assumed it would be. But it was worth it, as it has enabled me to get rid of a `Result` as well.

After a rebase from the main, adding a `set_timeout` function to the ApiClient should be trivial.
I've ended up going with a default of 30 seconds for the timeout, as it's a more typical value than 10 seconds.

**Comment by skoky** [comment]
I have rebased to your latest main. I feel i broke it. Let me analyze this in more details

**Comment by skoky** [comment]
I updated the rust API. Not sure how we can test python code to make sure it works. Do you like way of Rust and Python API is designed now?

**Comment by mihai-dinculescu** [comment]
Nice. This is a lot more ergonomic.
Maybe it should be called `with_timeout` or just `timeout` instead of `set_timeout`, considering it follows the builder pattern that returns Self?

The Python wrapper has examples that can be run [like this](https://github.com/mihai-dinculescu/tapo?tab=readme-ov-file#examples-1).

**Comment by skoky** [comment]
I followed you style of setting params. Let me know if it make sense

**Comment by mihai-dinculescu** [comment]
Shouldn't the Python wrapper follow the same behavior of the Rust API with the `with_timeout` instead of having timeout in the constructor?

**Comment by WhySoBad** [comment]
How is this pull request going along? I would really like to see this feature as soon as possible.

Let me know if I can help somewhere by contributing to this issue

**Comment by mihai-dinculescu** [comment]
Sorry for the long delay; work got in the way.
I've mulled this over and decided to go with your suggestion. While I would like the Python API to remain as consistent as possible with the Rust one, I find it worthwhile to diverge in some cases to make it Pythonic.

**Review by mihai-dinculescu — APPROVED** [review]

**Comment by skoky** [comment]
@mihai-dinculescu  thanks for merging. Can you please release new version with python as well? I wish to have it in my project. Thanks

**Comment by mihai-dinculescu** [comment]
It's been released.

**Pull request merged**
