### PR TITLE
Add get_current_power to power monitoring plugs

### PR DESCRIPTION
**Pull request by Michal-Szczepaniak**
Related issue https://github.com/mihai-dinculescu/tapo/issues/109

I've somehow managed to implement it (and tested it) without prior rust knowledge

### CODE REVIEW

**Comment by mihai-dinculescu** [comment]
Thank you for this.

Are you sure this is your first time writing Rust? :) The PR is almost flawless.
Can you please run `cargo fmt` and commit the changes?

**Comment by Michal-Szczepaniak** [comment]
Sure will do. 

First time writing rust,
but not first time programming :P

**Comment by mihai-dinculescu** [comment]
Ah, `cargo clippy` has a few complaints as well.

**Comment by Michal-Szczepaniak** [comment]
yes yes I'm already ahead of you :P

**Review by mihai-dinculescu — APPROVED** [review]

**Pull request merged**
