### PR TITLE
Add a serde alias to deserialize from either `overheated` or `overheated_status`

### LINKED ISSUE #248: tapo-py :- 0.3.1 getting error while calling get_device_info
### Description
When trying to fetch device information using `get_device_info()` for a P110 device, the following error occurs:

```python
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Cell In[18], line 1
----> 1 device_info = await device.get_device_info()
Exception: Serde(Error("missing field `overheated`", line: 1, column: 832))
```

### Environment
- Python version: 3.11
- Tapo-py version: 0.3.1

### Steps to Reproduce
1. Create a device object for P110
2. Call `await device.get_device_info()`

### Expected Behavior
The function should return the device information without any errors.

image

### PR DESCRIPTION
**Pull request by padenot**
This should fix #248 while ensuring older devices keep working if the library is updated but not the firmare of the device.

I only have P110 and P115, but updated all other devices -- those are untested but it should be harmless if it hasn't been renamed there.

### CODE REVIEW

**Comment by padenot** [comment]
The field has changed from a `bool` to a string, and we should probably map to an `enum`, but I don't know of the possible variants just yet, so I've left it as a `bool`. We can fix this later, this fixes the library.

**Comment by mihai-dinculescu** [comment]
It would be best to update the plugs only for now and have the field called `overheat_status` with a non-optional enum.
I've left a comment on https://github.com/mihai-dinculescu/tapo/issues/248 with the enum values.

If you're happy to make the Rust changes, I can do the Python ones.

**Comment by padenot** [comment]
> It would be best to update the plugs only for now and have the field called `overheat_status` with a non-optional enum.

Updated. For some reason the up-to-date p110 and p115 don't have this overheated field right now so I left it as optional.

**Comment by mihai-dinculescu** [comment]
Thank you for this.
I’ve reviewed it and made some adjustments that I believe are appropriate, so that it can be released today.

**Pull request merged**
